SUPABASE_URL="https://oilamfxxqjopuopgskfc.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbGFtZnh4cWpvcHVvcGdza2ZjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzA0Njg1NiwiZXhwIjoyMDc4NjIyODU2fQ.qylNpJ8ceebrD1q9QZ6CnYf0z2rxmcfjZfdXdqdaobc"
